version: "3.0"

services:
  rabbitmq:
    image: rabbitmq:management
    mem_limit: 512m
    mem_reservation: 128M
    ports:
      - 5672:5672   # The standard AMQP protocol port
      - 15672:15672 # HTTP management UI
    
  consumer:
    image: emileyray/consumer:latest
    mem_limit: 512m
    mem_reservation: 128M
    build:
      context: .
    container_name: consumer
    depends_on:
      - rabbitmq
    restart: always
    network_mode: host

  producer:
    image: emileyray/producer:latest
    mem_limit: 512m
    mem_reservation: 128M
    build:
      context: .
    container_name: producer
    depends_on:
      - rabbitmq
    restart: always
    network_mode: host

